### PR TITLE
Finalise AWS / Hub issue

### LINKED ISSUE #935: Ansible inithook won't work as expected when launched on AWS MP
While working on another matter, I noticed that the Ansible inithook [explicitly copies the generated SSH key to the root user](https://github.com/turnkeylinux-apps/ansible/blob/master/overlay/usr/lib/inithooks/firstboot.d/50ansible-key#L11-L13). 

While that's fine for  most of the builds; AWS Marketplace require the root account to be disabled. So instead we provide an "admin" user account. So the Ansilbe inithook should probably check to see if `/home/admin` exists and if it does, use that instead.

Also it'd probably be a good idea to rename the inithook to be consistent and inline with other appliances. I.e. instead of [`inithooks/bin/setpass_key.py`](https://github.com/turnkeylinux-apps/ansible/blob/master/overlay/usr/lib/inithooks/bin/setpass_key.py), it should really be `inithooks/bin/ansible.py`.

### PR DESCRIPTION
**Pull request by JedMeister**
This is a replacement PR for #16 - closes turnkeylinux/tracker#935.

It also addresses [concerns](https://github.com/turnkeylinux-apps/ansible/pull/16#issuecomment-370858948) for raised by @Dude4Linux with my [proposed](https://github.com/turnkeylinux-apps/ansible/pull/16#issuecomment-370579863) removal of the Ansible directories in `/etc/skel`.

It also includes refactoring of code to make the Ansible appliance more consistent with other appliances and some other improvements, including a version bump for Ansible (to v2.4.3.0).

For the issue to be completely resolved WRT AWS/Hub, a new version of inithooks, which includes https://github.com/turnkeylinux/inithooks/commit/41d1d307dbfec7a4ea5f35f25c02620a528d118a is also required.

### CODE REVIEW

**Comment by JedMeister** [comment]
Oops, I actually meant to leave this unmerged for discussion, but as I've merged it now, I'll leave things be. If we need new modifications, then we can simply open a new PR.

**Comment by Dude4Linux** [comment]
@JedMeister I finally got around to building this latest version on my "TKLDev v15" container. The first thing I see is that the 'ansible' account is still using /etc/skel and not /etc/skel-ansible.  Since having the files in skel causes a problem with AWS, I think I'm comfortable with just moving the files to /home/ansible.
Second, it's been awhile since default directory layout was implemented. I want to check and make sure they are up to date with current best-practices.
Third, version 2.5.0 is now available with significant improvements.  If we continue to use pip installs, we can use the latest version.  Ansible version 2.4.3 is now available via stretch-backports so that would be an option if we wanted to get away from pip installs in favor of apt-get.

**Comment by Dude4Linux** [comment]
@JedMeister I think is see the problem re: issue one.
conf.d/main modifies the useradd command to use /etc/skel-ansible, but then uses adduser to create the ansible user.
```
# configure default new user skel dir to be /etc/skel-ansible
CONF=/etc/default/useradd
sed -i "/SKEL=/ {s|^# ||; s|/etc/skel.*|/etc/skel-${ADMIN_USER}|}" $CONF
...
# create admins group, ansible user and sudo privs
addgroup --system admins
adduser --disabled-login --gecos 'ansible user' $ADMIN_USER
```
I could modify /etc/adduser to also use /etc/skel-ansible, but if the issue is not wanting the extra files in the 'admin' user created for AWS, then I think we have a conundrum. Leaving adduser and useradd using different skel dirs is bound to confuse end users.  Frankly I think it might be best to just put the files in overlay/home/ansible and leave the /etc/skel directory alone.

**Comment by JedMeister** [comment]
@Dude4Linux 

Thanks for having a look at this.

> I think I'm comfortable with just moving the files to /home/ansible.

Ok, then let's just "undo" my dirty hack and move those files to the ansible user's `$HOME`.

> Second, it's been awhile since default directory layout was implemented. I want to check and make sure they are up to date with current best-practices.

No worries. If you're able to have a look at that and update, then that'd be awesome.

> Third, version 2.5.0 is now available with significant improvements. If we continue to use pip installs, we can use the latest version. Ansible version 2.4.3 is now available via stretch-backports so that would be an option if we wanted to get away from pip installs in favor of apt-get.

I'm happy to stay with the pip install. Especially if it has significant improvements. So let's go with that and include the newer 2.5.0 version.

>  could modify /etc/adduser to also use /etc/skel-ansible, but if the issue is not wanting the extra files in the 'admin' user created for AWS, then I think we have a conundrum. Leaving adduser and useradd using different skel dirs is bound to confuse end users. Frankly I think it might be best to just put the files in overlay/home/ansible and leave the /etc/skel directory alone.

Agreed. It was a dirty workaround for the issue, but without removing those files altogether, I couldn't see any particularly good options... I thought that I had tested it fairly well though, so not sure why it wasn't working as intended.

Regardless, as you're ok with just adding it to Ansible's `$HOME` then lets just do that.

Are you able to take care of these changes? If so, please update the changelog and replace @OnGle's signoff with your own name, email and the date you do the work (please edit the existing v15.0 entry rather than adding a new one). 

----

There is no huge rush on this, as you can see we still haven't released v15.0RC of core yet. And the v15.0 appliances will be released in batches of 10-20.

FWIW we've been having some teething problems with our reproducible builds and I'm also struggling to get the updated package of `busybox-initramfs` to build to Alon's required specs. 

As an aside (I only mention it because I recall you were using Drupal?!) I'll also need to sidetrack a little on the latest Drupal sec updates. I hope to do a blog post today and we'll be releasing updated v14.3 builds of both Drupal appliances in coming days.

Hopefully we'll have all those issues resolved ASAP and get a v15.0RC of core out the door really soon...

**Comment by Dude4Linux** [comment]
I took a look at the directory layout vs current Ansible® best-practice and decided the current layout was okay. I made the change to version 2.5.0 and it seems to be running okay.  

I fixed another problem I found with keychain running in containers.  The current practice was to set the filename using $HOSTNAME at build time when it defaulted to the appliance name i.e. 'ansible'. With containers the hostname changes when the container is created, so a container named ansible-test, will through an error.  I changed the keychain setup to use $(hostname) at runtime.

I ran across a page of Ansible trademark requirements.  I think we need to update the documentation to comply.

I'll rollback the changes you made and then move the files from /etc/skel to /home/ansible, update the change log and issue a new PR.

**Comment by Dude4Linux** [comment]
When I tried moving the files to ``/home/ansible``, I ran into the problem that ``overlay`` files are put in place before ``conf.d/main`` creates the ``ansible`` user.  This blocks the copying of the ``/etc/skel`` files and aborts the build.  My memory is fuzzy but I think this is why I put the files in ``/etc/skel`` in the first place.
I decided to leave the files in ``/etc/skel-ansible`` and just copy them from there after creating the ``ansible`` user.  Then I discovered I could just specify the environment var ``SKEL`` on the command line before ``adduser``.
```
# create admins group, ansible user and sudo privs
addgroup --system admins
SKEL=/etc/skel-ansible adduser --disabled-login --gecos 'ansible user' $ADMIN_USER
echo $ADMIN_USER:$ADMIN_PASS | chpasswd
usermod -a -G admins $ADMIN_USER
passwd -l $ADMIN_USER # lock account (AWS workaround; setting passwd reenables)
```
I've addressed all the other issues we've discussed and think I'm ready to issue a new PR.  Should I reference this PR #17, or the original tracker issue #935?  Or do I need to open a new issue?

**Comment by Dude4Linux** [comment]
@JedMeister @OnGle I was just browsing the Ansible documentation and came across their recommendation for installing on Debian.  Apparently Ansible is maintaining the Ubuntu PPA and although it says ``trusty``, I confirmed that it has the latest stable Ansible release 2.5.0 which is newer than available through ``stretch-backports``.  Using this instead of a pip install would make it easier to install updates, but I guess there is no support for automatically applying ``security`` updates.

> Latest Releases Via Apt (Debian)
> Debian users may leverage the same source as the Ubuntu PPA.
> 
> Add the following line to /etc/apt/sources.list:
> 
> deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
> Then run these commands:
> 
> $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
> $ sudo apt-get update
> $ sudo apt-get install ansible

Let me know if you want me to make this change.

**Comment by Dude4Linux** [comment]
@JedMeister @OnGle One more change that I would like to make has to do with an issue I've been struggling with since the first version of the Ansible appliance.  Typically, when creating and starting a container using Ansible, you use a wait_for condition statement to wait until port 22 becomes available, before using the container.  The problem is that with TurnKey apps, port 22 comes available well before the firstboot.d scripts finish.  I've had problems when running tests too soon before the initialization has completed.  Generally I've been using timed delay loops to wait a sufficient time, but that means the delay has to be long enough for the slowest appliance which can be several minutes so that means time is wasted waiting for the faster appliances.
I would like to add a state function to the turnkey_facts so that you could program something like
```
wait_for turnkey.state=initialized
```
I've been trying to figure out how to tell when all the firstboot.d scripts have completed. So far the only thing I can think of is to monitor the size of /etc/inithooks.conf. I think the last step performed by the initialization is to delete the contents of /etc/inithooks.conf leaving only one character (new-line) in the file. The trouble is I'm not sure this a reliable means for all TurnKey hosts.  It seems to work in containers because we are pre-seeding, but aren't there cases where /etc/inithooks.conf doesn't exist?  I suppose the test could be
```
if [ -f /etc/inithooks.conf ]; then
  if [ $( wc -c /etc/inithooks.conf ) -eq 1 ]; then
    state=initialized
  fi
else
  wait a long time
  state=initialized
fi
```
Can you think of any other way of testing if initialization is complete?  Checking if a task is running?

**Comment by JedMeister** [comment]
Hey @Dude4Linux - apologies on such a slow response...

> I was just browsing the Ansible documentation and came across their recommendation for installing on Debian. Apparently Ansible is maintaining the Ubuntu PPA and although it says trusty, I confirmed 
that it has the latest stable Ansible release 2.5.0 which is newer than available through stretch-backports. Using this instead of a pip install would make it easier to install updates, but I guess there is no support for automatically applying security updates.

Yeah, because Ubuntu and Debian aren't binary compatible, it's generally not recommended to use Ubuntu PPAs on Debian. However, seeing as Ansible is a python app, it shouldn't really be a problem in this case. Getting the version in Stretch backports updated (to what's in testing) is fairly straight forward, although it probably won't get updated as often (or as quickly) as Ansible's PPA.I really need to get more up to speed with Debian packaging so then I could take on a few of those things myself...

IMO from an end user perspective, there isn't probably a significant difference between an install from pip, PPA or backports (other than in backports, the version is older ATM; and probably won't be updated as regularly). None of them will get auto security updates. Using a proper repo install is probably more secure (than pip). So whilst I'm not super keen on using a PPA, that may be our best bet in this case...?!

> I've been trying to figure out how to tell when all the firstboot.d scripts have completed. So far the only thing I can think of is to monitor the size of /etc/inithooks.conf. I think the last step performed by the initialization is to delete the contents of /etc/inithooks.conf leaving only one character (new-line) in the file. The trouble is I'm not sure this a reliable means for all TurnKey hosts. It seems to work in containers because we are pre-seeding, but aren't there cases where /etc/inithooks.conf doesn't exist?

FWIW, all headless builds (inc containers, AMIs, Xen, OpenStack, etc) have a [`29preseed`](https://github.com/turnkeylinux/buildtasks/blob/master/patches/headless/overlay/usr/lib/inithooks/firstboot.d/29preseed) initihook. That only runs if they haven't been explicitly preseeded (it checks to see if `$INITHOOKS_CONF` exists - i.e. `/etc/inithooks.conf`). Other builds (e.g. ISO, VM) do not have `/etc/inithooks.conf` by default.

So your suggested script should do the job. Although in the case of a "headless" build that hasn't been preseeded, inithooks will run (via `29preseed` i.e. a "dumby" preseed) and bring up the initfence. FWIW, the initfence should probably come up sooner anyway, but that's a whole other issue... As the `29preseed` essentially runs like any other preseed, it will also clear the inithooks.conf file (as per any preseeded install), except it makes the inithooks run twice (first time sets random values and brings up the fence; second time runs interactively) and inithooks will be waiting at the terminal with an interactive session (via `dtach` - sort of like a super simple `screen` session). In that case, checking for dtach running may be an option? Although, I'm guessing in your case, you know that you presseded (or not) so perhaps that's not really useful?

AFAIK testing for the inithooks process itself won't be any good, as I'm pretty sure that inithooks actually runs as a daemon/service. Although TBH, I may be wrong...

Perhaps the best solution would be for inithooks to explicitly write out it's state somewhere? 

Also, it should write to a log file already IIRC (and if it doesn't it probably should!) So perhaps checking the state of that (last write time, last log entry, etc) could be another way?

Just thinking aloud really... I hope it's of some value.

**Pull request merged**
